Life/__init__.py
import os

from flask import Flask
from flask_bootstrap import Bootstrap
from flask_login import LoginManager,AnonymousUserMixin
from flask_sqlalchemy import SQLAlchemy
from flask_wtf import CSRFProtect
from flask_moment import Moment
from flask_avatars import Avatars
from flask_dropzone import Dropzone
from manage import config

bootstrap = Bootstrap()
db = SQLAlchemy()
moment = Moment()
avatars = Avatars()
csrf = CSRFProtect()
login_manager = LoginManager()
login_manager.login_view = 'auth.login'
dropzone = Dropzone()

@login_manager.user_loader
def load_user(user_id):
    from Life.models import User
    user = User.query.get(int(user_id))
    return user


class Guest(AnonymousUserMixin):

    def can(self,permission_name):
        return False

    @property
    def is_admin(self):
        return False

login_manager.anonymous_user = Guest

def create_app(config_name=None):
    if config_name is None:
        config_name = os.getenv('FLASK_CONFIG','development')

    app = Flask(__name__)
    app.config.from_object(config[config_name])
    app._static_folder = 'static'
    register_extensions(app)
    register_blueprints(app)

    return app

def register_extensions(app):
    bootstrap.init_app(app)
    login_manager.init_app(app)
    db.init_app(app)
    moment.init_app(app)
    csrf.init_app(app)
    avatars.init_app(app)
    dropzone.init_app(app)

def register_blueprints(app):
    from Life.blueprints.auth import auth_bp
    from Life.blueprints.main import main_bp
    app.register_blueprint(main_bp)
    app.register_blueprint(auth_bp,url_prefix='/auth')



app = create_app(os.getenv('FLASK_CONFIG','development'))

Life/blueprints/auth.py
from flask import url_for, render_template, flash, Blueprint
from flask_login import current_user, login_user, login_required, logout_user
from Life.models import User
from werkzeug.security import generate_password_hash
from werkzeug.utils import redirect

from Life.form.auth import RegisterForm, LoginForm

auth_bp = Blueprint('auth',__name__)

@auth_bp.route('/',methods=['GET','POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))
    form = RegisterForm()
    if form.validate_on_submit():
        email = form.email.data.lower()
        username = form.username.data
        password = form.password.data
        user = User()
        user.email = email
        user.username = username
        user.password_hash = generate_password_hash(password)

        if User.register(user):
            flash('注册成功','ok')
            return redirect(url_for('auth.register'))
    return render_template('auth/register.html', form=form)

@auth_bp.route('/login/',methods=['GET','POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data.lower()).first()
        if user is not None and user.validate_password(form.password.data):
            if login_user(user,form.remember_me.data):
                return redirect(url_for('main.index'))
            else:
                flash('登录失败','err')
                return redirect('login')
        flash('密码错误','err')
    return render_template('auth/login.html', form=form)

@auth_bp.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('main.index'))

Life/blueprints/main.py
import os

from flask import url_for, render_template, request, Blueprint, flash, make_response, send_from_directory, current_app
from flask_login import current_user, login_required
from werkzeug.utils import redirect

from Life import avatars
from Life.form.main import PostForm, CommentForm, EditProfileForm, UploadAvatarForm, CropAvatarForm
from Life.models import db, Post, Comment, User, Follow, Photo, Movie
from utils import rename_image,resize_photo

main_bp = Blueprint('main',__name__)

@main_bp.route('/',methods=['GET','POST'])
def index():
    form = PostForm()
    if current_user.is_authenticated and form.validate_on_submit():
        post = Post(body=form.body.data,author=current_user._get_current_object())
        db.session.add(post)
        db.session.flush()       #获取插入的id
        post_id = post.id
        db.session.commit()
        print(request.files)
        if form.photo.data.filename:
            for f in request.files.getlist('photo'):
                filename = rename_image(f.filename)
                print(filename)
                f.save(os.path.join(current_app.config['PHOTO_UPLOAD_PATH'], filename))
                s_filename = resize_photo(filename)
                photo = Photo(filename=filename,filename_s=s_filename,author=current_user._get_current_object(),post_id=post_id)
                db.session.add(photo)
                db.session.commit()
        if form.movie.data.filename:
            f = request.files.get('movie')
            filename = rename_image(f.filename)
            print(filename)
            f.save(os.path.join(current_app.config['MOVIE_UPLOAD_PATH'],filename))
            movie = Movie(filename=filename,author=current_user._get_current_object(),post_id=post_id)
            db.session.add(movie)
            db.session.commit()
        return redirect(url_for('main.index'))
    show_followed = False
    if current_user.is_authenticated:
        show_followed = bool(request.cookies.get('show_followed',''))
    if show_followed:
        query = current_user.followed_posts
    else:
        query = Post.query
    posts = query.order_by(Post.timestamp.desc())
    photos = Photo.query.all()
    movies = Movie.query.all()
    return render_template('main/index.html', show_followed=show_followed,form=form,posts=posts,photos=photos,movies=movies)

@main_bp.route('/post/<int:id>',methods=['GET','POST'])
@login_required
def post(id):
    post = Post.query.get_or_404(id)
    form = CommentForm()
    if form.validate_on_submit():
        comment = Comment(body=form.body.data,post=post,author=current_user._get_current_object())
        db.session.add(comment)
        db.session.commit()
        flash('评论成功')
        return redirect(url_for('main.post',id=post.id))
    comments = Comment.query.filter_by(post_id=id).order_by(Comment.timestamp.desc()).all()
    photos = Photo.query.all()
    movies = Movie.query.all()
    return render_template('main/post.html',post=post,form=form,comments=comments,photos=photos,movies=movies)

@main_bp.route('/post/<int:id>/edit',methods=['GET','POST'])
@login_required
def edit(id):
    post = Post.query.get_or_404(id)
    form = PostForm()
    if form.validate_on_submit():
        post.body = form.body.data
        db.session.add(post)
        db.session.commit()
        return  redirect(url_for('main.post',id=post.id))
    form.body.data = post.body
    return render_template('main/edit_post.html',form=form)

@main_bp.route('/post/<int:id>/delete',methods=['GET'])
@login_required
def delete(id):
    post = Post.query.get_or_404(id)
    user = User.query.filter_by(id=post.author_id).first()
    db.session.delete(post)
    db.session.commit()
    return redirect(url_for('main.user',username=user.username))

@main_bp.route('/user/<username>')
def user(username):
    user = User.query.filter_by(username=username).first_or_404()
    posts = user.posts.order_by(Post.timestamp.desc()).all()
    return render_template('main/user.html',user=user,posts=posts)


@main_bp.route('/follow/<username>')
@login_required
def follow(username):
    user = User.query.filter_by(username=username).first()
    if current_user.is_following(user):
        flash('你已经关注过了','err')
        return redirect(url_for('main.user',username=username))
    current_user.follow(user)
    db.session.commit()
    flash('关注成功','ok')
    return redirect(url_for('main.user',username=username))

@main_bp.route('/unfollow/<username>')
@login_required
def unfollow(username):
    user = User.query.filter_by(username=username).first()
    if not current_user.is_following(user):
        flash('未关注此用户','err')
        return redirect(url_for('main.user', username=username))
    current_user.unfollow(user)
    db.session.commit()
    flash('已取消关注','ok')
    return redirect(url_for('main.user', username=username))

@main_bp.route('/edit_profile',methods=['GET','POST'])
@login_required
def edit_profile():
    form = EditProfileForm()
    if form.validate_on_submit():
        current_user.username = form.username.data
        current_user.location =form.location.data
        current_user.about_me = form.about_me.data
        db.session.add(current_user._get_current_object())
        db.session.commit()
        return redirect(url_for('main.user',username=current_user.username))
    form.username.data = current_user.username
    form.location.data = current_user.location
    form.about_me.data = current_user.about_me
    return render_template('main/edit_profile.html',form=form)

@main_bp.route('/edit_profile/avatar',methods=['POST','GET'])
@login_required
def change_avatar():
    upload_form = UploadAvatarForm()
    crop_form = CropAvatarForm()
    return render_template('main/change_avatar.html',upload_form=upload_form,crop_form=crop_form)

@main_bp.route('/edit_profile/avatar/upload',methods=['POST'])
@login_required
def upload_avatar():
    form = UploadAvatarForm()
    if form.validate_on_submit():
        image = form.image.data
        filename = avatars.save_avatar(image)
        current_user.avatar_raw = filename
        db.session.commit()
    return redirect(url_for('main.change_avatar'))

@main_bp.route('/edit_profile/avatar/crop',methods=['POST'])
@login_required
def crop_avatar():
    form = CropAvatarForm()
    if form.validate_on_submit():
        x = form.x.data
        y = form.y.data
        w = form.w.data
        h = form.h.data
        filenames = avatars.crop_avatar(current_user.avatar_raw,x,y,w,h)
        current_user.avatar_s = filenames[0]
        current_user.avatar_m = filenames[1]
        current_user.avatar_l = filenames[2]
        db.session.commit()
    return redirect(url_for('main.edit_profile'))


@main_bp.route('/followers/<username>')
def followers(username):
    user = User.query.filter_by(username=username).first()
    pagination = user.followers.paginate(1,1,error_out=False)
    follows = [{'user':item.follower,'timestamp':item.timestamp} for item in pagination.items]
    return render_template('main/followers.html',user=user,follows=follows)

@main_bp.route('/followed_by/<username>')
def followed_by(username):
    user = User.query.filter_by(username=username).first()
    pagination = user.followed.paginate(1,1,error_out=False)
    follows = [{'user':item.followed,'timestamp':item.timestamp} for item in pagination.items]
    return render_template('main/followers.html',user=user,follows=follows)

@main_bp.route('/all')
@login_required
def show_all():
    res = make_response(redirect(url_for('main.index')))
    res.set_cookie('show_followed','',max_age=30*24*60*60)
    return res


@main_bp.route('/followed')
@login_required
def show_followed():
    res = make_response(redirect(url_for('main.index')))
    res.set_cookie('show_followed','1',max_age=30*24*60*60)
    return res


@main_bp.route('/avatars/<path:filename>')
def get_avatar(filename):
    return send_from_directory(current_app.config['AVATARS_SAVE_PATH'],filename)

@main_bp.route('/upload',methods=['GET','POST'])
def upload():
    if request.method == 'POST' and 'file' in request.files:
        f = request.files.get('file')
        filename = rename_image(f.filename)
        f.save(os.path.join(current_app.config['PHOTO_UPLOAD_PATH'], filename))
        # filename_s = resize_image(f, filename, current_app.config['ALBUMY_PHOTO_SIZE']['small'])
        # filename_m = resize_image(f, filename, current_app.config['ALBUMY_PHOTO_SIZE']['medium'])
        photo = Photo(
            filename=filename,
            # filename_s=filename_s,
            # filename_m=filename_m,
            author=current_user._get_current_object()
        )
        db.session.add(photo)
        db.session.commit()
    return render_template('main/upload.html')

Life/form/auth.py
from wtforms import StringField, PasswordField, SubmitField, BooleanField
from flask_wtf import FlaskForm
from wtforms.validators import DataRequired, Length, Regexp, EqualTo, ValidationError

from Life.models import User

class RegisterForm(FlaskForm):
    email = StringField('Email',validators=[DataRequired(),Length(1,64)])
    username = StringField('Username',validators=[DataRequired(),Length(1,20),Regexp('^[a-zA-Z0-9]*$',message='用户名由字母和数字组成')])
    password = PasswordField('Password',validators=[DataRequired(),Length(8,128),EqualTo('password2')])
    password2 = PasswordField('Confirm',validators=[DataRequired()])
    submit = SubmitField('注册',render_kw={
            'class':"btn btn-lg btn-success btn-sm" ,
        }
)

    def validate_email(self,field):
        if User.query.filter_by(email=field.data).first():
            raise ValidationError('邮箱已存在')

    def validate_username(self,field):
        if User.query.filter_by(username=field.data).first():
            raise ValidationError('用户名已存在')

class LoginForm(FlaskForm):
    email = StringField('Email', validators=[DataRequired(), Length(1, 64)])
    password = PasswordField('Password', validators=[DataRequired(), Length(8, 128)])
    remember_me = BooleanField('记住我')
    submit = SubmitField('登陆',render_kw={'class':"btn btn-lg btn-info btn-sm"})

Life/form/main.py
from flask_pagedown.fields import PageDownField
from flask_wtf.file import FileRequired, FileAllowed
from wtforms import StringField, PasswordField, SubmitField, TextAreaField, HiddenField, FileField,MultipleFileField
from flask_wtf import FlaskForm
from wtforms.validators import DataRequired, Length, Regexp, EqualTo, ValidationError

class PostForm(FlaskForm):
    body = PageDownField('mind',validators=[DataRequired()])
    photo = FileField('图片',render_kw={'class':"btn btn-success",'type':'file','id':'file','multiple':''})
    movie = FileField('电影')
    submit = SubmitField('发布')


class CommentForm(FlaskForm):
    body = StringField('comment',validators=[DataRequired()])
    submit = SubmitField('发布')

class EditProfileForm(FlaskForm):
    username = StringField('用户名',validators=[Length(0,64)])
    location = StringField('位置',validators=[Length(0,64)])
    about_me = TextAreaField('个性签名')
    submit = SubmitField('确认修改')

class UploadAvatarForm(FlaskForm):
    image = FileField('上传',validators=[FileRequired(),FileAllowed(['jpg','png'],'文件格式应该为.jpg或.png')])
    submit = SubmitField('上传')

class CropAvatarForm(FlaskForm):
    x = HiddenField()
    y = HiddenField()
    w = HiddenField()
    h = HiddenField()
    submit = SubmitField('裁剪并上传')

Life/templates/main/edit_post.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
    {{ wtf.quick_form(form) }}

{% endblock %}

Life/templates/main/edit_profile.html
{% extends 'base.html' %}
{% import "bootstrap/wtf.html" as wtf %}

{% block content %}
<div class="page-header">
    <h1>Edit Your Profile</h1>
</div>
<div class="col-md-4">
<img class="rounded img-fluid avatar-s profile-popover"
                                     data-href="{{ url_for('main.change_avatar', username=current_user.username) }}"
                                     src="{{ url_for('main.get_avatar', filename=current_user.avatar_m) }}">
    <a href="{{ url_for('main.change_avatar') }}">上传头像</a>
    {{ wtf.quick_form(form) }}
</div>
{% endblock %}

Life/templates/main/index.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{#{% import "_macros.html" as macros %}#}

{% block title %}index{% endblock %}



{% block content %}
<div>
    {% if current_user.is_authenticated %}
        <h1>Hello, {% if current_user.is_authenticated %}{{ current_user.username }}{% else %}Stranger{% endif %}!</h1>

    {{ wtf.quick_form(form) }}
    {% endif %}

<br>

</div>
<div class="post-tabs">
    <ul class="nav nav-tabs">
        <li class="nav-item"> <a  class="nav-link {% if not show_followed %} active {% endif %}" href="{{ url_for('main.show_all') }}">所有</a></li>
        {% if current_user.is_authenticated %}
        <li class="nav-item" ><a  class="nav-link {% if show_followed %} active {% endif %}" href="{{ url_for('main.show_followed') }}">关注的人</a></li>
        {% endif %}
    </ul>
{#    {% include '_posts.html' %}#}
</div>


    {% for post in posts %}
{#        <div class="container">#}

        <div class="card">
        <div class="card-body">
        <div class="card-title">
             <img class="rounded img-fluid avatar-s profile-popover"
                                     data-href="{{ url_for('main.user', username=post.author.username) }}"
                                     src="{{ url_for('main.get_avatar', filename=post.author.avatar_s) }}">
                            <a href="{{ url_for('main.user',username=post.author.username) }}">{{ post.author.username }}</a> <small data-toggle="tooltip" data-placement="top"
                           data-timestamp="&#12288;{{ post.timestamp.strftime('%Y-%m-%dT%H:%M:%SZ') }}"
                    data-delay="500">{{ moment(post.timestamp).fromNow() }}</small></div>


            <div class="card-text">
                {% if post.body_html %}
                    {{ post.body_html | safe }}
                {% else %}
                    {{ post.body }}
                {% endif %}
            <br>
            {% for photo in photos %}
                {% if photo.post_id == post.id %}
               <a href="{{ url_for('static', filename='photos/%s' %(photo.filename)) }}"><img  src="{{ url_for('static', filename='photos/%s' %(photo.filename_s) ) }}"></a>&nbsp;
                {% endif %}
                {% endfor %}
            {% for movie in movies %}
            {% if movie.post_id == post.id %}
                <video  width="320" height="240" controls="controls" >
                 <source src="{{ url_for('static', filename='movies/%s' %(movie.filename)) }}" type="video/mp4">
                 <source src="{{ url_for('static', filename='movies/%s' %(movie.filename)) }}" type="video/ogg">
                    Sorry, your browser doesn't support embedded videos.</video>
                {% endif %}
                {% endfor %}
            </div>
            <div class="post-footer">
                        {% if post.author_id== current_user.id %}
                <a href="{{ url_for('main.delete',id=post.id) }}">
                    <span style="float:right" class="badge badge-dark">删除</span>
                </a>
            {% endif %}
                            <a href="{{ url_for('main.post',id=post.id) }}">
                    <span style="float:right" class="badge badge-success">评论</span>
                </a>

                {% if current_user == post.author %}
                <a href="{{ url_for('main.edit',id=post.id) }}">
                    <span style="float:right" class="badge badge-primary">编辑</span>
                </a>
{#                {% elif current_user.is_administrator() %}#}
{#                <a href="#">#}
{#                    <span class="label label-danger">Edit [Admin]</span>#}
{#                </a>#}
                {% endif %}
                <a href="#">
                    <span  class="label label-default"></span>
                </a>

            </div>
        </div>
        </div>
{#        </div>#}
&nbsp;
    {% endfor %}

{#{% if pagination %}#}
{#<div class="pagination">#}
{#    {{ macros.pagination_widget(pagination, '.index') }}#}
{#</div>#}
{#{% endif %}#}
{#{% endblock %}#}

{#{% block scripts %}#}
{#{{ super() }}#}
{#{{ pagedown.include_pagedown() }}#}
{% endblock %}

Life/templates/main/post.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}

       <div class="card">
        <div class="card-body">
        <div class="card-title">
            <img class="rounded img-fluid avatar-s profile-popover"
                                     data-href="{{ url_for('main.user', username=post.author.username) }}"
                                     src="{{ url_for('main.get_avatar', filename=post.author.avatar_s) }}">
            <a href="#">{{ post.author.username }}</a> <small data-toggle="tooltip" data-placement="top"
                           data-timestamp="&#12288;{{ post.timestamp.strftime('%Y-%m-%dT%H:%M:%SZ') }}"
                    data-delay="500">{{ moment(post.timestamp).fromNow() }}</small></div>


<div class="card-text">
                {% if post.body_html %}
                    {{ post.body_html | safe }}
                {% else %}
                    {{ post.body }}
                {% endif %}
            <br>
            {% for photo in photos %}
                {% if photo.post_id == post.id %}
               <a href="{{ url_for('static', filename='photos/%s' %(photo.filename)) }}"><img  src="{{ url_for('static', filename='photos/%s' %(photo.filename_s) ) }}"></a>&nbsp;
                {% endif %}
                {% endfor %}
            {% for movie in movies %}
            {% if movie.post_id == post.id %}
                <video  width="320" height="240" controls="controls" >
                 <source src="{{ url_for('static', filename='movies/%s' %(movie.filename)) }}" type="video/mp4">
                 <source src="{{ url_for('static', filename='movies/%s' %(movie.filename)) }}" type="video/ogg">
                    Sorry, your browser doesn't support embedded videos.</video>
                {% endif %}
                {% endfor %}
            </div>
            <div class="post-footer">
                        {% if post.author_id== current_user.id %}
                <a href="{{ url_for('main.delete',id=post.id) }}">
                    <span style="float:right" class="badge badge-dark">删除</span>
                </a>
            {% endif %}
                            <a href="{{ url_for('main.post',id=post.id) }}">
                    <span style="float:right" class="badge badge-success">评论</span>
                </a>

                {% if current_user == post.author %}
                <a href="{{ url_for('main.edit',id=post.id) }}">
                    <span style="float:right" class="badge badge-primary">编辑</span>
                </a>
{#                {% elif current_user.is_administrator() %}#}
{#                <a href="#">#}
{#                    <span class="label label-danger">Edit [Admin]</span>#}
{#                </a>#}
                {% endif %}
                <a href="#">
                    <span  class="label label-default"></span>
                </a>

            </div>
        </div>
       </div>
        <br>
        {{ wtf.quick_form(form) }}
        {% for comment in comments %}
            <li class="comment">
{#        <div class="comment-thumbnail">#}
{#            <a href="{{ url_for('.user', username=comment.author.username) }}">#}
{#                <img class="img-rounded profile-thumbnail" src="{{ comment.author.gravatar(size=40) }}">#}
{#            </a>#}
{#        </div>#}
        <div class="comment-content">

        <img class="rounded img-fluid avatar-s profile-popover"
                                     data-href="{{ url_for('main.user', username=comment.author.username) }}"
                                     src="{{ url_for('main.get_avatar', filename=comment.author.avatar_s) }}">
            <a href="#">{{ post.author.username }}</a>  <small data-toggle="tooltip" data-placement="top"
                           data-timestamp="&#12288;{{ post.timestamp.strftime('%Y-%m-%dT%H:%M:%SZ') }}"
                    data-delay="500">{{ moment(comment.timestamp).fromNow() }}</small></div>

            <div class="comment-body">
{#                {% if comment.disabled %}#}
{#                <p><i>This comment has been disabled by a moderator.</i></p>#}
{#                {% endif %}#}
{#                {% if moderate or not comment.disabled %}#}
                    {% if comment.body_html %}
                        {{ comment.body_html | safe }}
                    {% else %}
                        {{ comment.body }}
                    {% endif %}
{#                {% endif %}#}
            </div>
{#            {% if moderate %}#}
{#                <br>#}
{#                {% if comment.disabled %}#}
{#                <a class="btn btn-default btn-xs" href="{{ url_for('.moderate_enable', id=comment.id, page=page) }}">Enable</a>#}
{#                {% else %}#}
{#                <a class="btn btn-danger btn-xs" href="{{ url_for('.moderate_disable', id=comment.id, page=page) }}">Disable</a>#}
{#                {% endif %}#}
{#            {% endif %}#}


    </li>
    {% endfor %}


{% endblock %}

Life/templates/main/user.html
{% extends 'base.html' %}

{% block content %}

<div class="page-header">
{#    <img class="img-rounded profile-thumbnail" src="{{ user.gravatar(size=256) }}">#}
    <div class="profile-header">

    <img class="rounded img-fluid avatar-s profile-popover"
                                     data-href="{{ url_for('main.user', username=user.username) }}"
                                     src="{{ url_for('main.get_avatar', filename=user.avatar_m) }}">
        <h1>{{ user.username }}</h1>

            <p><a href="{{ url_for('main.edit_profile') }}">修改信息</a></p>
        <p>
            {% if user.location %}
                来自 <a href="http://maps.google.com/?q={{ user.location }}">{{ user.location }}</a><br>
            {% endif %}
        </p>

{#        {% if current_user.is_administrator() %}#}
{#        <p><a href="mailto:{{ user.email }}">{{ user.email }}</a></p>#}
{#        {% endif %}#}
        {% if user.about_me %}<p>个性签名：{{ user.about_me }}</p>{% endif %}
        <p>用户注册于：{{ moment(user.member_since).format('L') }}. 上次登录时间： {{ moment(user.last_seen).fromNow() }}.</p>
        <p>共发表{{ user.posts.count() }} 条微博</p>
        <p>
        {% if current_user.id != user.id %}
                {% if not current_user.is_following(user) %}
                <a href="{{ url_for('main.follow', username=user.username) }}" class="btn btn-primary">关注</a>
                {% else %}
                <a href="{{ url_for('main.unfollow',username=user.username) }}" class="btn btn-primary">取消关注</a>
                {% endif %}
        {% endif %}
            <a href="{{ url_for('main.followers', username=user.username) }}">粉丝: <span class="badge">{{ user.followers.count()  }}</span></a>
            <a href="{{ url_for('main.followed_by', username=user.username) }}">关注: <span class="badge">{{ user.followed.count()  }}</span></a>
            {% if current_user.is_authenticated and user != current_user and user.is_following(current_user) %}
            | <span class="label label-default">已关注你</span>
            {% endif %}
        </p>
{#        <p>#}
{#            {% if user == current_user %}#}
{#            <a class="btn btn-default" href="{{ url_for('.edit_profile') }}">Edit Profile</a>#}
{#            {% endif %}#}
{#            {% if current_user.is_administrator() %}#}
{#            <a class="btn btn-danger" href="{{ url_for('.edit_profile_admin', id=user.id) }}">Edit Profile [Admin]</a>#}
{#            {% endif %}#}
{#        </p>#}
    </div>
</div>
    {% for post in posts %}
{#        <div class="container">#}

        <div class="card">
        <div class="card-body">
        <div class="card-title">

            <img class="rounded img-fluid avatar-s profile-popover"
                                     data-href="{{ url_for('main.user', username=post.author.username) }}"
                                     src="{{ url_for('main.get_avatar', filename=post.author.avatar_s) }}">
            <a href="{{ url_for('main.user',username=post.author.username) }}">{{ post.author.username }}</a> <small data-toggle="tooltip" data-placement="top"
                           data-timestamp="&#12288;{{ post.timestamp.strftime('%Y-%m-%dT%H:%M:%SZ') }}"
                    data-delay="500">{{ moment(post.timestamp).fromNow() }}</small></div>


          <div class="card-text">
                {% if post.body_html %}
                    {{ post.body_html | safe }}
                {% else %}
                    {{ post.body }}
                {% endif %}
            <br>
            {% for photo in photos %}
                {% if photo.post_id == post.id %}
               <a href="{{ url_for('static', filename='photos/%s' %(photo.filename)) }}"><img  src="{{ url_for('static', filename='photos/%s' %(photo.filename_s) ) }}"></a>&nbsp;
                {% endif %}
                {% endfor %}
            {% for movie in movies %}
            {% if movie.post_id == post.id %}
                <video  width="320" height="240" controls="controls" >
                 <source src="{{ url_for('static', filename='movies/%s' %(movie.filename)) }}" type="video/mp4">
                 <source src="{{ url_for('static', filename='movies/%s' %(movie.filename)) }}" type="video/ogg">
                    Sorry, your browser doesn't support embedded videos.</video>
                {% endif %}
                {% endfor %}
            </div>
            <div class="post-footer">
                        {% if post.author_id== current_user.id %}
                <a href="{{ url_for('main.delete',id=post.id) }}">
                    <span style="float:right" class="badge badge-dark">删除</span>
                </a>
            {% endif %}
                            <a href="{{ url_for('main.post',id=post.id) }}">
                    <span style="float:right" class="badge badge-success">评论</span>
                </a>

                {% if current_user == post.author %}
                <a href="{{ url_for('main.edit',id=post.id) }}">
                    <span style="float:right" class="badge badge-primary">编辑</span>
                </a>
{#                {% elif current_user.is_administrator() %}#}
{#                <a href="#">#}
{#                    <span class="label label-danger">Edit [Admin]</span>#}
{#                </a>#}
                {% endif %}
                <a href="#">
                    <span  class="label label-default"></span>
                </a>

            </div>
        </div>
        </div>
{#        </div>#}
&nbsp;
    {% endfor %}


{% endblock %}